apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supplychain-cacerts-job
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: supplychain-cacerts-job
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dev
        namespace: flux-dev
      chart: platforms/hyperledger-fabric/charts/generate_cacerts
  values:
    metadata:
      name: supplychain
      component_name: supplychain-net
      namespace: supplychain-net    
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      role: vault-role
      address: vault-0.vault-internal:8200
      authpath: devsupplychain-net-auth
      secretcryptoprefix: secret/data/devwebapp/config/data/crypto/ordererOrganizations/supplychain-net/ca
      secretcredentialsprefix: secret/data/devwebapp/config/data/credentials/supplychain-net/ca/supplychain
      serviceaccountname: vault-auth
      imagesecretname: regcred
      
    ca:
      subject: /C=GB/ST=London/L=London/O=Orderer/CN=ca.supplychain-net.org1ambassador.blockchaincloudpoc.com
